name: Gradle Build and Release

on:
  push:
    tags:
      - 'v*' # Trigger on version tags
  workflow_dispatch: # This enables manual triggering
    inputs:
      release_tag:
        description: 'Release tag (e.g., v1.0.0)'
        required: true
        type: string
      release_name:
        description: 'Release name'
        required: true
        type: string
      is_draft:
        description: 'Create as draft release'
        required: true
        type: boolean
        default: false
      is_prerelease:
        description: 'Create as pre-release'
        required: true
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for creating releases
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21' # You can change this to your preferred Java version
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.release_tag || github.ref_name }}
        name: ${{ github.event.inputs.release_name || github.ref_name }}
        files: |
          build/libs/*.jar
        generate_release_notes: true
        draft: ${{ github.event.inputs.is_draft || false }}
        prerelease: ${{ github.event.inputs.is_prerelease || false }}
